plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.6'
	id 'io.spring.dependency-management' version '1.1.7'
    id 'jacoco'
    id 'maven-publish'
    id 'org.springframework.cloud.contract' version '4.3.0'
}

group = 'profect.group1'
version = '0.0.1-SNAPSHOT'
description = 'project in profect'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
    mavenLocal()
	mavenCentral()
}

ext {
	set('springCloudVersion', "2025.0.0")
}


//jacoco
jacoco {
    toolVersion = "0.8.12"
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        html.required.set(true)
        xml.required = true
        csv.required = false
        html.outputLocation = layout.buildDirectory.dir('reports/jacoco')
    }

    afterEvaluate {
        classDirectories.setFrom(
                files(classDirectories.files.collect {
                    fileTree(dir: it, include: [
                            '**/service/**',
                            '**/controller/**',
                            '**/repository/**'
                    ],
                    exclude: [
                            '**/category/**',
                            '**/stock/**',
                            '**/review/**',
                            '**/dto/**',
                            '**/config/**',
                            '**/exception/**',
                            '**/enums/**',
                            '**/settings/**',
                            '**/mapper'
                    ])
                })
        )
    }
}

contracts {
    baseClassForTests = 'profect.group1.goormdotcom.contractTest.BaseTestClass'
    testFramework = 'JUNIT5'
    contractsDslDir = file('src/contractTest/resources/contracts')
}

publishing {
    publications {
        stubs(MavenPublication) {
            // stubs JAR을 publish 대상으로 추가
            artifact(tasks.named('verifierStubsJar'))
            // (선택) artifactId를 stubs용으로 분리하고 싶으면
            // artifactId = 'product-service-stubs'
        }
    }
}

dependencies {

	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-aop'

	implementation 'org.springframework.boot:spring-boot-starter-actuator'

	// Micrometer -> Prometheus 측정 데이터 전송
	implementation 'io.micrometer:micrometer-registry-prometheus'

	// feign client
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    // spring-data-redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // circuit braker
    implementation 'io.github.resilience4j:resilience4j-spring-boot3'
    implementation 'io.github.resilience4j:resilience4j-annotations'

    // Spring Cloud Contract
    testImplementation 'org.springframework.cloud:spring-cloud-starter-contract-verifier' // producer
    testImplementation "org.springframework.cloud:spring-cloud-starter-contract-stub-runner" // consumer

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.0'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// PostgreSQL
	runtimeOnly 'org.postgresql:postgresql:42.7.5'
	
	// H2 Database (for development)
	runtimeOnly 'com.h2database:h2'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'

    //aws s3
    implementation platform('software.amazon.awssdk:bom:2.31.36')
    implementation 'software.amazon.awssdk:s3'

    //JSON 직/역직렬화
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    //.env
    implementation 'me.paulschwarz:spring-dotenv:4.0.0'

    //Opentelemetry
    implementation "io.opentelemetry:opentelemetry-api"

    //kafka
    implementation 'org.springframework.kafka:spring-kafka'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
