spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 200
        format_sql: true

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

  aws:
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
    cloudfront:
      domain: ${AWS_CLOUDFRONT_DOMAIN}

springdoc:
  use-fqn: true

server:
  port: ${SERVER_PORT}

service:
  user:
    url: ${USER_SERVICE_URL}
  product:
    url: ${PRODUCT_SERVICE_URL}
  order:
    url: ${ORDER_SERVICE_URL}
  payment:
    url: ${PAYMENT_SERVICE_URL}

stock:
  adjust:
    retry:
      base-off-ms: ${BASE_OFF_MS}
      max-retries: ${MAX_RETRIES}