spring:
  application:
    name: "product-service"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
      timeout: ${REDIS_COMMAND_TIMEOUT} # redis-server 호출 했을 때 대기 시간
      connect-timeout: ${REDIS_CONNECT_TIMEOUT} # redis-server 연결시 대기 시간

springdoc:
  use-fqn: true

server:
  port: ${SERVER_PORT}

service:
  product:
    url: ${PRODUCT_SERVICE_URL}
  order:
    url: ${ORDER_SERVICE_URL}
  payment:
    url: ${PAYMENT_SERVICE_URL}

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
  cloudfront:
    domain: ${AWS_CLOUDFRONT_DOMAIN}
    default-image: ${AWS_DEFAULT_IMAGE}

stock:
  adjust:
    retry:
      base-off-ms: ${BASE_OFF_MS}
      max-retries: ${MAX_RETRIES}

