apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  # Spring
  SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
  SERVER_PORT: "${SERVER_PORT}"

  # Database (PostgreSQL)
  DB_DRIVER: "${DB_DRIVER}"
  DB_URL: "${DB_URL}"

  # Internal service endpoints (예시)
  PRODUCT_SERVICE_URL: "${PRODUCT_SERVICE_URL}"
  ORDER_SERVICE_URL: "${ORDER_SERVICE_URL}"
  PAYMENT_SERVICE_URL: "${PAYMENT_SERVICE_URL}"

  BASE_OFF_MS: "${BASE_OFF_MS}"
  MAX_RETRIES: "${MAX_RETRIES}"

  AWS_CLOUDFRONT_DOMAIN: "${AWS_CLOUDFRONT_DOMAIN}"
  AWS_DEFAULT_IMAGE: "${AWS_DEFAULT_IMAGE}"

  REDIS_HOST: "${REDIS_HOST}"
  REDIS_PORT: "${REDIS_PORT}"
  REDIS_DATABASE: "${REDIS_DATABASE}"
  REDIS_CONNECT_TIMEOUT: "${REDIS_CONNECT_TIMEOUT}"
  REDIS_COMMAND_TIMEOUT: "${REDIS_COMMAND_TIMEOUT}"
  REDIS_SSL_ENABLED: "${REDIS_SSL_ENABLED}"

  PRODUCT_ORIGIN_MAX_CONCURRENT_CALLS: "${PRODUCT_ORIGIN_MAX_CONCURRENT_CALLS}"
  PRODUCT_ORIGIN_MAX_WAIT_DURATION: "${PRODUCT_ORIGIN_MAX_WAIT_DURATION}"
  PRODUCT_ORIGIN_LIMIT_FOR_PERIOD: "${PRODUCT_ORIGIN_LIMIT_FOR_PERIOD}"
  PRODUCT_ORIGIN_LIMIT_REFRESH_PERIOD: "${PRODUCT_ORIGIN_LIMIT_REFRESH_PERIOD}"
  PRODUCT_ORIGIN_TIMEOUT_DURATION: "${PRODUCT_ORIGIN_TIMEOUT_DURATION}"
