apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
type: Opaque
stringData:
  # Database
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"

  REDIS_PASSWORD: "${REDIS_PASSWORD}"

  AWS_S3_ACCESS_KEY: "${AWS_S3_ACCESS_KEY}"
  AWS_S3_SECRET_KEY: "${AWS_S3_SECRET_KEY}"
  AWS_S3_BUCKET: "${AWS_S3_BUCKET}"
  AWS_S3_REGION: "${AWS_S3_REGION}"
